# Using Artifacts (for passing files between jobs)

name: Example Pipeline

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate file
        run: |
          echo "Hello, world!" > myfile.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myfile
          path: myfile.txt

  test:
    runs-on: windows-latest
    needs: build  # This ensures the 'build' job completes before this one starts
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myfile

      - name: Use downloaded file
        run: |
          type myfile.txt
